# Setup
title:            Max Davidowitz
tagline:          'Max Davidowitz'
description:      'Max Davidowitz Portfolio'
url:              https://maxzin8.github.io/_portfolio

paginate:         5

# About and contact
author:
  name:           'Max Davidowitz'
  url:            https://www.linkedin.com/in/max-davidowitz-eng8/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
